{
 "title": "GLBC / Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace (filtered to glbc namespaces)",
    "query": "label_values(glbc_controller_reconcile_total, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Managed ingress objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Ingress objects",
   "type": "stat",
   "description": "Shows the total number of managed ingress objects",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(glbc_ingress_managed_object_total{namespace=\"$namespace\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Ingress Admissions",
   "type": "graph",
   "description": "Shows the Ingress admission rate to load balancers, and the 90, 95 & 99th percentiles for how long admissions took.",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Admission time" }
   ],
   "targets": [
    {
     "expr": "sum(rate(glbc_ingress_managed_object_time_to_admission_count{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "Admission Rate"
    },
    {
     "expr": "histogram_quantile(0.9, sum  by(le) (rate(glbc_ingress_managed_object_time_to_admission_bucket{namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "90th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(glbc_ingress_managed_object_time_to_admission_bucket{namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(glbc_ingress_managed_object_time_to_admission_bucket{namespace=\"$namespace\"}[$__range])))",
     "legendFormat": "99th %ile"
    }
   ]
  },
  {
   "title": "AWS Route53 - Rate, Errors & Duration (RED Method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "AWS Route53 Requests",
   "type": "stat",
   "description": "Shows aggregate data on DNS requests to AWS Route53 for the selected time range.\nNote that if a different DNS provider than Route53 is used, these values may be 0.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glbc_aws_route53_request_total{namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(increase(glbc_aws_route53_request_errors_total{namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "AWS Route53 Requests",
   "type": "graph",
   "description": "Shows the rate of requests to Route53 for the selected time range. Note that if a different DNS provider than Route53 is used, these values may be 0.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(glbc_aws_route53_request_total{namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(rate(glbc_aws_route53_request_errors_total{namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Total Errors"
    }
   ]
  },
  {
   "title": "TLS Certificates - Rate, Errors & Duration (RED Method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "TLS Cert Issuer",
   "type": "stat",
   "description": "The identifier of the certificate issuer configured for the controller in the selected namespace",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glbc_tls_certificate_secret_count{namespace=\"$namespace\"}",
     "legendFormat": "{{issuer}}"
    }
   ]
  },
  {
   "title": "TLS Cert Requests",
   "type": "graph",
   "description": "Shows the rate of certificate requests for the selected time range.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(rate(glbc_tls_certificate_request_total{namespace=\"$namespace\"}[$__range])) by (namespace)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(glbc_tls_certificate_request_total{namespace=\"$namespace\", result=\"succeeded\"}[$__range])) by(namespace)",
     "legendFormat": "Total Succeeded"
    },
    {
     "expr": "sum(rate(glbc_tls_certificate_request_total{namespace=\"$namespace\", result=\"failed\"}[$__range])) by (namespace)",
     "legendFormat": "Total Failed"
    },
    {
     "expr": "sum(rate(glbc_tls_certificate_secret_count{namespace=\"$namespace\" }[$__range])) by (namespace)",
     "legendFormat": "Total Secrets"
    },
    {
     "expr": "sum(rate(glbc_tls_certificate_pending_request_count{namespace=\"$namespace\"}[$__range])) by (namespace)",
     "legendFormat": "Total Pending"
    },
    {
     "expr": "sum(rate(glbc_tls_certificate_issuance_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\"}[$__range])) by (namespace) - sum(rate(glbc_tls_certificate_issuance_duration_seconds_bucket{namespace=\"$namespace\" , le=\"300\"}[$__range]))  by (namespace)",
     "legendFormat": "Total > 5min"
    }
   ]
  },
  {
   "title": "TLS Cert Requests",
   "type": "stat",
   "description": "Shows aggregate data on certificate requests for the selected time range.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(glbc_tls_certificate_request_total{namespace=\"$namespace\"}[$__range])) by (namespace)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_request_total{namespace=\"$namespace\", result=\"succeeded\"}[$__range])) by(namespace)",
     "legendFormat": "Total Succeeded"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_request_total{namespace=\"$namespace\", result=\"failed\"}[$__range])) by (namespace)",
     "legendFormat": "Total Failed"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_secret_count{namespace=\"$namespace\" }[$__range])) by (namespace)",
     "legendFormat": "Total Secrets"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_pending_request_count{namespace=\"$namespace\"}[$__range])) by (namespace)",
     "legendFormat": "Total Pending"
    },
    {
     "expr": "sum(increase(glbc_tls_certificate_issuance_duration_seconds_bucket{namespace=\"$namespace\", le=\"+Inf\"}[$__range])) by (namespace) - sum(increase(glbc_tls_certificate_issuance_duration_seconds_bucket{namespace=\"$namespace\" , le=\"300\"}[$__range]))  by (namespace)",
     "legendFormat": "Total > 5m"
    }
   ]
  },
  {
   "title": "Pods - Utilisation, Saturation & Errors (USE Method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Pod Statuses",
   "type": "stat",
   "description": "Shows the number of pods by status in the selected namespace. Note this is an 'Instant' value i.e. it uses the latest value instead of querying over a range.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"$namespace\"}) by(phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Shows pod CPU usage for each pod in the namespace. If set, pod CPU requests and limits are also shown. The legend includes a suffix of the pod name.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "CPU Limits {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "CPU Requests {{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\"}[1m])) by (pod)",
     "legendFormat": "CPU Usage {{pod}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "stat",
   "description": "Shows the number of container restarts (by pod) over the chosen time range for the selected namespace.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"$namespace\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Shows pod memory usage in MiB (based on RSS) for each pod in the namespace. If set, pod memory requests and limits are also shown. The legend includes a suffix of the pod name.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "Pod Memory Requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "Pod Memory Limits {{pod}}"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\", container=\"manager\"}) by (pod)",
     "legendFormat": "Pod Memory {{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "description": "Shows the total number of Goroutines by pod. Only 1 line is expected for the glbc pod.",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{namespace=\"$namespace\"}) by(pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation & Workers - Rate, Errors & Duration (RED Method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 }
  },
  {
   "title": "Controller Reconcile Rate (success)",
   "type": "graph",
   "description": "Shows the rate of successful reconcile loops",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(glbc_controller_reconcile_total{namespace=\"$namespace\",result=\"success\"}[5m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "graph",
   "description": "Shows the rate of resources being queued for processing by each controller.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{namespace=\"$namespace\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Controller Reconcile Rate (error)",
   "type": "graph",
   "description": "Shows the rate of failed/erroring reconcile loops",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(glbc_controller_reconcile_total{namespace=\"$namespace\",result=\"error\"}[5m])) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth",
   "type": "graph",
   "description": "Shows the queue size for each resource controller.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{namespace=\"$namespace\"}[5m])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency",
   "type": "graph",
   "description": "Shows the queue processing latency for each resource controller.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "KCP API Requests - Rate, Errors & Duration (RED Method)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 }
  },
  {
   "title": "Request Rate - Non 5xx",
   "type": "graph",
   "description": "Shows the rate of non 5xx requests per HTTP method.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rest_client_requests_total{namespace=\"$namespace\",code!~\"5.*\"}[5m])",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Request Rate - 5xx",
   "type": "graph",
   "description": "Shows the rate of 5xx requests per HTTP method.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(rest_client_requests_total{namespace=\"$namespace\",code=~\"5.*\"}[5m])",
     "legendFormat": "{{code}} {{method}}"
    }
   ]
  },
  {
   "title": "Request Times",
   "type": "graph",
   "description": "Shows the average request times & various percentiles aggregated across all requests.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(rest_client_request_latency_seconds_bucket{namespace=~\"$namespace\"}[$__range])) by(le))",
     "legendFormat": "99th %ile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(rest_client_request_latency_seconds_bucket{namespace=~\"$namespace\"}[$__range])) by(le))",
     "legendFormat": "95th %ile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(rest_client_request_latency_seconds_bucket{namespace=~\"$namespace\"}[$__range])) by(le))",
     "legendFormat": "90th %ile"
    },
    {
     "expr": "sum(rest_client_request_latency_seconds_sum{namespace=~\"$namespace\"}) / sum(rest_client_request_latency_seconds_count{namespace=~\"$namespace\"})",
     "legendFormat": "Average"
    }
   ]
  }
 ]
}