
resources:
  - ingress.yaml
  - dashboards/glbc-dashboard.yaml
  - https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/release-0.10/manifests/grafana-deployment.yaml

# Deploy Grafana Dashboards
configMapGenerator:
- name: glbc-dashboard
  namespace: monitoring
  behavior: replace
  files:
    # configkey is used as key
    - glbc_overview.json=dashboards/glbc.json

# Patch grafana deployment to include dashboard configmaps
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: grafana
  path: grafana_patch.yaml